---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-test
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app-container
        image: ktoshiya/gin-test:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        imagePullPolicy: Always
        env:
        - name: POSTGRES_HOST
          value: psql.default.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: gin-test
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    role: app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
spec:
  replicas: 1
  serviceName: psql
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
      - name: psql-container
        image: postgres:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: init-sql-configmap
          mountPath: /docker-entrypoint-initdb.d
        - name: datadir
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-sql-configmap
          configMap:
            name: init-db-sql
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: psql
spec:
  type: ClusterIP
  ports:
    - name: "psql-port"
      protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    role: db
